### ISSUE TITLE
Option to warn only for lint and format issues

### ISSUE THREAD

**Issue by nvx** [bufbuild/buf-action#136]
Being able to warn for lint and format issues but not fail the action entirely would be handy.

Continue on error type semantics no longer works as it did with the old now-deprecated actions because you can't specify it to apply for eg only lint and format while retaining it for breaking.

**Comment by emcfarlane** [comment]
Theres currently no parameters to control this behaviour and the defaults are intended to be a good default more most users. However, the parameters for the action allow for configuration. Your behaviour could be achieved by splitting out the steps in two, allowing failure on the first, and continuing to the other:
```yaml
# Run lint and format checks, allowing failure.
- uses: bufbuild/buf-action@v1
  continue-on-error: true
  with:
    token: ${{ secrets.BUF_TOKEN }}
    lint: ${{ github.event_name == 'pull_request' }}
    format: ${{ github.event_name == 'pull_request' }}
    breaking: flase
    push: false
    archive: false
# Proceed with other checks and push flow.
- uses: bufbuild/buf-action@v1
  with:
    lint: false 
    format: false
```
See the parameters config for more information. You can also use the action just to install and setup `buf` but run the steps, see this [example](https://github.com/bufbuild/buf-action/blob/main/examples/only-setup-defaults/buf-ci.yaml).
