### ISSUE TITLE
Broken builds on GitHub Enterprise for bufaction v1.1

### ISSUE THREAD

**Issue by cbusbey** [bufbuild/buf-action#143]
Getting build failures on GHE for a previously stable build using `bufaction/buf-action@v1` following the v1.1 release of buf-action 

```
Run bufbuild/buf-action@v1
  with:
    version: 1.40.0
    pr_comment: false
    domain: buf.build
    github_actor: xxxxxxx
    github_token: ***
    setup_only: false
    exclude_imports: false
    lint: true
    format: true
    breaking: true
    push: false
    push_disable_create: false
    archive: false
  env:
    BUF_VERSION: 1.40.0
    GO_VERSION: xxxxxxxxxx
Running on GitHub Enterprise, using public GitHub API.
Warning: public_github_token not set, GitHub API requests may be limited
Error: Parameter token or opts.auth is required
```

Locking to `bufaction/buf-action@v1.0` resolves this issue.

**Comment by emcfarlane** [comment]
Hi @cbusbey sorry to hear your having issues. We think the issue is on configuration of the REST client for public GitHub:  https://github.com/bufbuild/buf-action/pull/144 . This is not required for your use case, and the initial client should now be fixed. Would you be willing to test this?

```
- uses: bufbuild/buf-action@ed/fixEnterpriseOcktokit
```

Thanks for reporting this issue.

**Comment by cbusbey** [comment]
Thanks @emcfarlane - the patch works 👍  

```
Run bufbuild/buf-action@ed/fixEnterpriseOcktokit
  with:
    version: 1.40.0
    pr_comment: false
    domain: buf.build
    github_actor: xxxxxxx
    github_token: ***
    setup_only: false
    exclude_imports: false
    lint: true
    format: true
    breaking: true
    push: false
    push_disable_create: false
    archive: false
  env:
    BUF_VERSION: 1.40.0
    GO_VERSION: 1.23.0
Running on GitHub Enterprise, using public GitHub API.
```
