### ISSUE TITLE
Set `filter=tree:0` for `breaking_against` as default when supported

### ISSUE THREAD

**Issue by CGA1123** [bufbuild/buf-action#147]
`buf` 1.50.x adds support for an additional parameter for `git` inputs `filter` which allows for treeless and shallow clones.

This improves the performance of `breaking` significantly when run against larger repositories.

Making this a default would likely best be held off on until the next release of the `buf` CLI, which improves support for authentication via `BUF_INPUT_HTTPS_{USERNAME,PASSWORD}` environment variables, which this action relies for auth to GitHub.

Related: bufbuild/buf#3707
Related: #142

**Comment by emcfarlane** [comment]
Thanks for creating the issue! As a workaround for now you can also specify the breaking against as a local directory and do the git checkout using the checkout action: https://github.com/bufbuild/buf-action?tab=readme-ov-file#specify-the-input-directory
```yaml
- uses: actions/checkout@v4
  with:
    path: head
- uses: actions/checkout@v4
  with:
    path: base
    ref: ${{ github.event.pull_request.base.sha }}
- uses: bufbuild/buf-action@v1
  with:
    input: head
    breaking_against: base
```
