### ISSUE TITLE
Question: How to exclude files from `breaking` check

### ISSUE THREAD

**Issue by FWinklerOfficial** [bufbuild/buf-action#184]
Hi there,

I have configured the buf action in a github workflow to check for breaking changes.
My module contains the following files:

```
payload-spec
 +-- my_module
        +-- protoc
         |      +-- gen
         |             +-- jsonschema
         |                    +-- v1
         |                           +-- options.proto
         +-- acme
                +-- v1
                       +-- acme.proto
```

I want the `breaking` check to check the `acme.proto` file, but they way it is currently configured, it also checks the `options.proto` file, which is something I don't want to happen, since `options.proto` is only a kind of configuration file.

I am using the following config:

```yaml
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-action@v1
        with:
          input: "payload-spec/my_module"
          version: 1.50.0 
          public_github_token: ${{ secrets.BUF_TOKEN }}
          lint: true
          format: true
          push: false
          breaking: true
          breaking_against: https://link-to-my-repo.git#branch=main,subdir=payload-spec/my_module/acme/v1
```

However that throws an error:

```
Failure: failed to build input "payload-spec/my_module/acme/v1" because it is contained by module at path "payload-spec/my_module" specified in your configuration, you must provide the workspace or module as the input, and filter to this path using --path.
```

I did find no mention about how to configure `--path` in the [buf action documentation](https://buf.build/docs/reference/inputs/#breaking-change-detection).

All I would like to make sure is that `options.proto` is excluded from the breaking changes check. How do I best configure the `breaking_against` part?

Thanks!
