### ISSUE TITLE
Fail to differentiate between multiple separate checks in same PR

### ISSUE THREAD

**Issue by arxeiss** [bufbuild/buf-action#51]
Hello,

I'm trying to migrate from separate actions you provided earlier into this all-in-one action.
But I have spotted an issue with our 2 buf modules. We have `proto/public` and `proto/internal` folders so I have 2 Github actions. See example of action yaml below. We trigger that action only when there is a change inside specific folder.

Reason we have 2 separate actions is breaking check. For public, we cannot do breaking change (except rare case) but for internal, we can. As we deploy all together (not best approach, but for now it speeds up development), so we are OK with small risk.

However, your action in the first run created 2 comments with same wording. So it is not possible to differentiate between them.

And during second round, action modified just 1 comment, and the second was left unchanged.

Do you plan to support multiple buf-action runs within same PR?

Thank you

Same file we have twice, once with `proto/public` and second with `proto/internal`.
```yaml
---
name: buf check
on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: master
        paths:
            - proto/public/**

permissions:
    contents: read
    pull-requests: write

jobs:
    build:
        name: Perform a buf check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codebase
              uses: actions/checkout@v4

            - name: buf setup
              uses: bufbuild/buf-action@v0.2.1
              with:
                  input: proto/public
                  breaking_against: https://github.com/${{github.repository}}.git#branch=master,subdir=proto/public

```

![image](https://github.com/user-attachments/assets/81c6ae1a-d413-453a-b5b4-52338f58df3f)
