### ISSUE TITLE
Input does not meet YAML 1.2 "Core Schema" specification

### ISSUE THREAD

**Issue by krak3n** [bufbuild/buf-action#66]
Hey Team

I tried your label skipping example:

```yaml
# This workflow skips checks when `buf skip` is used in the commit message.
name: Buf CI
on:
  push:
  delete:
permissions:
  contents: read
jobs:
  buf:      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          lint: |
            github.event_name == 'push' && \
            !contains(github.event.head_commit.message, 'buf skip lint')
          format: |
            github.event_name == 'push' && \
            !contains(github.event.head_commit.message, 'buf skip format')
          breaking: |
            github.event_name == 'push' && \
            !contains(github.event.head_commit.message, 'buf skip breaking')
```

When the action runs it errors with:

```
Error: Input does not meet YAML 1.2 "Core Schema" specification: lint
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```
