### ISSUE TITLE
Push doesn't work on Pull Requests

### ISSUE THREAD

**Issue by krak3n** [bufbuild/buf-action#67]
# What

Pushing doesn't seem to work on pull requests:

```yaml
name: Buf CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: write
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Head"
        uses: actions/checkout@v4
        with:
          path: head

      - name: "Checkout Base"
        uses: actions/checkout@v4
        with:
          path: base
          ref: ${{ github.event.pull_request.base.sha }}

      - name: "CI"
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: head/proto
          breaking_against: base/proto
          lint: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip lint') }}
          format: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip format') }}
          breaking: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip breaking') }}
          push: true
```

The action fails with:

```
Failure: no tags or branches found for HEAD, 2eeca03a29ce1a3352942fdac233319df2f3e7c8
```

However if I run `buf push` locally it works perfectly fine:

```
buf push --error-format github-actions --exclude-unnamed --git-metadata --create proto
```
