### ISSUE TITLE
Pushing on a tag doesn't create the tag in the schema registry

### ISSUE THREAD

**Issue by krak3n** [bufbuild/buf-action#68]
# What

If the action runs on a push to a tag, for example creating a release the push to the schema registry does not also create the tag.

For example:

```yaml
name: Buf CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: write
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Head"
        uses: actions/checkout@v4
        with:
          path: head

      - name: "Checkout Base"
        uses: actions/checkout@v4
        with:
          path: base
          ref: ${{ github.event.pull_request.base.sha }}

      - name: "CI"
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: head/proto
          breaking_against: base/proto
          lint: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip lint') }}
          format: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip format') }}
          breaking: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip breaking') }}
          push: ${{ github.event_name == 'push' }}
```

Then creating a release (e.g v1.2.3) which also creates a tag should not only push to the BSR but should also create the tag (label) in the BSR.

Essentially this:

```
buf push --tag ${{ github.event.release.tag_name }} ./proto
```

**Comment by krak3n** [comment]
managed to work around it by creating a workflow specifically for tag pushes:

```yaml
name: BSR

on:
  push:
    tags:
      - v**

jobs:
  buf:
    name: Buf

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: proto
          lint: false
          format: false
          breaking: false
          push: true
```
