### ISSUE TITLE
Unable to cache more than one version of buf

### ISSUE THREAD

**Issue by jeffj254** [bufbuild/buf-action#71]
We use self-hosted runners with a hostedtoolcache of various tools and versions that our developers use. We build the cache following GitHub's recommendation here: https://docs.github.com/en/enterprise-server@3.11/admin/managing-github-actions-for-your-enterprise/managing-access-to-actions-from-githubcom/setting-up-the-tool-cache-on-self-hosted-runners-without-internet-access

The process is pretty simple, you basically just call the `setup-` actions for whatever tools you need and then tarball up the hostedtoolcache directory. Extract that into your runner image build and off you go.

When I try to do this with buf I get an error while trying to setup the second version that the requested version doesn't match what is in the PATH. Is it possible to add an additional parameter to allow a second version to be cached?

example workflow:
```
      # Buf
      - name: setup buf 1.35.1
        uses: bufbuild/buf-action@v1
        with:
          version: 1.35.1
          setup_only: true
      - name: setup buf 1.44.0
        uses: bufbuild/buf-action@v1
        with:
          version: 1.44.0
          setup_only: true
```

Error message with this workflow:
```
Run bufbuild/buf-action@v1
Using the version of buf from the input: 1.44.0
Using buf (1.35.1) found in $PATH
Error: The version of buf (1.35.1) does not equal the resolved version (1.44.0)
```
