### ISSUE TITLE
Running this action on Gitea

### ISSUE THREAD

**Issue by chocolatkey** [bufbuild/buf-action#75]
When attempting to run this action using [Gitea actions](https://docs.gitea.com/usage/actions/overview) on a private Gitea instance, the action fails:
```
Using buf (1.45.0) found in $PATH
[command]/opt/homebrew/bin/buf registry login buf.build --token-stdin
Logged in as chocolatkey. Credentials saved to /Users/mayo/.netrc.
[command]/opt/homebrew/bin/buf config ls-modules --format name
buf.build/kintsugi/kinproto
[command]/opt/homebrew/bin/buf build --error-format github-actions
[command]/opt/homebrew/bin/buf push --error-format github-actions --exclude-unnamed --git-metadata --create
Usage:
  buf push <source> [flags]
Flags:
      [...OMMITTED FOR BREVITY...]
Failure: unable to determine source control URL for this repository; only GitHub/GitLab/BitBucket are supported
::error::Failed push
```

This seems to come from https://github.com/bufbuild/buf/blob/main/private/buf/cmd/buf/command/push/push.go#L496 . Is there any way to get this running on Gitea? I don't see why using a platform aside from GitHub/GitLab/BitBucket should block using `buf push --error-format github-actions --exclude-unnamed --git-metadata --create`

**Comment by emcfarlane** [comment]
Hey @chocolatkey , this is an issue with the how the `--git-metadata` resolves the label name and source control URL. Currently `buf` only supports the registries listed. To workaround this issue you can invoke the `push` step using a custom run section:
```yaml
- uses: bufbuild/buf-action@v1
  with:
    token: ${{ secrets.BUF_TOKEN }}
    push: false. # Disable push to customize git metadata
- if: ${{ github.event_name == 'push' }}
  env:
    BRANCH_NAME: ${{ github.ref_name }}
    SOURCE_CONTROL_URL: ${{ github.event.head_commit.url }}
  run: |
    buf push --error-format github-actions --exclude-unnamed --create \
      --label $BRANCH_NAME \
      --source-control-url $SOURCE_CONTROL_URL
```
