### ISSUE TITLE
buf.yaml v2 Skipping push, no named modules detected

### ISSUE THREAD

**Issue by krak3n** [bufbuild/buf-action#76]
# What

Push does not seem to work when running a `buf.yaml` at version 2:

```yaml
version: v2
modules:
  - path: proto/
    name: buf.custom.domain/foo/bar
breaking:
  ignore_unstable_packages: true
  use:
    - FILE
lint:
  use:
    - STANDARD
```

Workflows:

```yaml
name: Push

on:
  push:
    paths:
      - "**.proto"
      - "**/buf.yaml"
      - "**/buf.lock"
      - "**/README.md"

permissions:
  contents: read

jobs:
  buf:
    name: Buf

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          domain: buf.custom.domain
          input: proto
          push: true
```

Debug output from the action:

```
##[debug]Skipping push, no named modules detected
```

I can also push with `buf push --label foo` locally using `buf` at `v1.46.0`.

`buf config ls-modules --format name` lists `buf.custom.domain/foo/bar`

`buf build --error-format github-actions proto` lists no output.
