### ISSUE TITLE
Feature Request: support Buf tokens for different BSR instances

### ISSUE THREAD

**Issue by oliversun9** [bufbuild/buf-action#79]
It would be nice to be able to specify:

```
- uses: bufbuild/buf-action@v1
  with:
    tokens:
      buf.build: ${{ secrets.BUF_TOKEN }}
      private.buf.build: ${{ secrets.PRIVATE_BUF_TOKEN }}
```
and `tokens` would be mutually exclusive with `token`.

**Comment by emcfarlane** [comment]
Multiple logins for different registries can be used by calling the action with the `setup_only` parameter flag set for multiple registries:

```
  - uses: bufbuild/buf-action@v1
    with:
      token: ${{ secrets.BUF_TOKEN }}
      setup_only: true
  - uses: bufbuild/buf-action@v1
    with:
      token: ${{ secrets.PRIVATE_BUF_TOKEN }}
      domain: private.buf.build
      setup_only: true
  - uses: bufbuild/buf-action@v1
```
Support for multiple registries is usually in error, with users wanting to have all the dependencies on a single BSR instance. So hesitant that this feature is needed.

**Comment by soggycactus** [comment]
@emcfarlane Is it not possible to publish different modules to different registries? Our use case is that we have some protobuf packages which we want to be public, and others which we want to be private. 

I am using the following configuration:

```
      - name: Setup Buf for private BSR SDKs
        uses: bufbuild/buf-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.PRIVATE_BUF_TOKEN }}
          setup_only: true
          domain: my-private-registry.example.com
      - name: Setup Buf for public BSR SDKs
        uses: bufbuild/buf-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.PUBLIC_BUF_TOKEN }}
          setup_only: true
      - uses: bufbuild/buf-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: "1.45.0"
          push: ${{ github.ref == 'refs/heads/main' }}
          breaking_against: '${{ github.event.repository.clone_url }}#branch=main,ref=HEAD,subdir=proto'
```

But I get the error `Failure: cannot upload content for multiple registries at once: my-private-registry.example.com, buf.build`
