### ISSUE TITLE
Allow continue-on-error

### ISSUE THREAD

**Issue by gowriter** [bufbuild/buf-action#83]
Hi Bufbuild team,

After exploring ways to integrate buf format into our CI workflow, I discovered your buf-action and was excited about the possibility of simplifying our current CI implementation by leveraging this action.

However, I encountered an issue that prevents me from replicating the expected behavior as demonstrated in the [Summary Comment section of your documentation](https://github.com/bufbuild/buf-action/tree/main?tab=readme-ov-file#summary-comment), as well replicate the steps listed below.

Problem
The CI workflow stops whenever an error occurs in one of the steps (e.g., linting or breaking change detection). 

As a result
The subsequent steps are skipped.
The summary comment is not posted to the pull request, even when the pr_comment input is enabled.

Expected Behavior
The CI should continue executing subsequent steps after an error and provide a summary comment on the pull request, detailing the results of each step (successful or failed).

Screenshot of the Issue
Here’s an example where the CI stops prematurely, and the summary comment is never created: 
<img width="859" alt="Error from CI" src="https://github.com/user-attachments/assets/2b14a165-c550-42cb-b384-f54c8a77b411" />

Request
Could you provide the option continue_on_error?

Thank you for your time and this great project!

Our current steps are:
```
- uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ token }}
          version: "1.34.0"

      - name: Run Buf Lint
        uses: bufbuild/buf-lint-action@v1
        continue-on-error: true

      - name: Run Buf Breaking
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: "some url"
        continue-on-error: true
```

we would like using this instead:
```
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Buf CLI
        uses: bufbuild/buf-action@v1
        with:
          version: 1.35.0
          github_token: ${{ stoken }}
          pr_comment: true
          push: false
          format: false
          lint: true
          breaking: true
          archive: false
          breaking_against: "some url"
```

**Comment by gowriter** [comment]
https://github.com/bufbuild/buf-action?tab=readme-ov-file#skip-the-breaking-change-detection-step

this solved it actually

**Comment by gowriter** [comment]
this was required as well:
```
pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  delete:
permissions:
  contents: read
  pull-requests: write
```
